import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from '../component/Header'
import Main from '../component/Main'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Cookie Stand</title>
        <meta name = "description" content = "Generated by create next app"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <Header>

      </Header>
      
      <Main>


      </Main>
      <p>
        Report Table coming soon .. ;)
      </p>
    </div>
  )
}
